### ISSUE TITLE
It's fucked

### ISSUE THREAD

**Issue by ZlatyChlapec** [m-krajcovic/sketchio#1]
![image](https://user-images.githubusercontent.com/6187861/30418750-556b79be-9934-11e7-9c32-2fa67a8ffb33.png)

When new players are joining there is this shit popping up at the bottom and eventually filling your entire screen so you can't play anymore.

Please fix or I'll be forced to look for alternatives to use :(

**Comment by m-krajcovic** [comment]
Are you sure it fills entire screen? It has max height set. Either way, I will do something about it. 
Thanks for the feedback

**Comment by m-krajcovic** [comment]
fixed in 8f103fe4fe8ecccf7fa479386dc208631d586a68
